# Generated by Django 4.1 on 2022-09-03 05:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=5)),
                ('birth', models.DateField(verbose_name='Birthday')),
                ('phone', models.CharField(max_length=25)),
                ('personality', models.CharField(choices=[('', 'Select a personality'), ('i am outgoing', 'I am outgoing'), ('i am sociable', 'I am sociable'), ('i am antisocial', 'I am antisocial'), ('i am discreet', 'I am discreet'), ('i am serious', 'I am serious')], max_length=50, null=True)),
                ('salary', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('experience', models.BooleanField(null=True)),
                ('smoker', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='resume', verbose_name='Resume')),
                ('image', models.ImageField(blank=True, upload_to='photo', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Situation', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=50, null=True)),
                ('company_note', models.TextField(blank=True)),
                ('frameworks', multiselectfield.db.fields.MultiSelectField(choices=[('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django'), ('Flask', 'Flask'), ('Vue', 'Vue'), ('Others', 'Others')], default='', max_length=39)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('Golang', 'Golang'), ('C++)', 'C++)'), ('Others', 'Others')], default='', max_length=41)),
                ('databases', multiselectfield.db.fields.MultiSelectField(choices=[('MySql', 'MySql'), ('Postgree', 'Postgree'), ('MongoDB', 'MongoDB'), ('Sqlite', 'SQLite'), ('Oracle', 'Oracle'), ('Others', 'Others')], default='', max_length=43)),
                ('libraries', multiselectfield.db.fields.MultiSelectField(choices=[('Ajax', 'Ajax'), ('Jquery', 'Jquery'), ('React.js', 'React.js'), ('Keras', 'Keras'), ('Tensorflow', 'Tensorflow'), ('Others', 'Others')], default='', max_length=44)),
                ('mobile', multiselectfield.db.fields.MultiSelectField(choices=[('React Native', 'React Native'), ('Ionic', 'Ionic'), ('Flutter', 'Flutter'), ('Kivy', 'Kivy'), ('Xamarin', 'Xamarin'), ('Others', 'Others')], default='', max_length=46)),
                ('others', multiselectfield.db.fields.MultiSelectField(choices=[('UML', 'UML'), ('Firebase', 'Firebase'), ('Docker', 'Docker'), ('GIT', 'GIT'), ('GraphQL', 'GraphQL'), ('Others', 'Others')], default='', max_length=38)),
                ('institution', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('started_course', models.DateField()),
                ('finished_course', models.DateField()),
                ('about_course', models.TextField()),
                ('status_course', models.CharField(choices=[('', 'Select Your Status'), ("I'm studying", "I'm studying"), ('I took a break', 'I took a break'), ('Completed', 'Completed')], max_length=50, null=True)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('started_job', models.DateField()),
                ('finished_job', models.DateField()),
                ('about_job', models.TextField()),
                ('employed', models.BooleanField(null=True, verbose_name='I am Employed')),
                ('remote', models.BooleanField(null=True, verbose_name='I agree to work remotly')),
                ('travel', models.BooleanField(null=True, verbose_name="I'm avaliable for travel")),
            ],
        ),
    ]
