# Generated by Django 4.1 on 2022-09-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='job',
            field=models.CharField(max_length=5, verbose_name='Job Code'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='message',
            field=models.TextField(verbose_name='Presentation'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='salary',
            field=models.CharField(max_length=50, verbose_name='Salary Expectation'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='smoker',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10),
        ),
    ]
