# Generated by Django 4.1 on 2022-09-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_candidate_job_alter_candidate_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='smoker',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', max_length=10),
        ),
    ]
