# Generated by Django 4.1 on 2022-09-04 13:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_candidate_smoker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MySql', 'MySql'), ('Postgree', 'Postgree'), ('MongoDB', 'MongoDB'), ('Sqlite', 'SQLite'), ('Oracle', 'Oracle'), ('Others', 'Others')], max_length=43),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django'), ('Flask', 'Flask'), ('Vue', 'Vue'), ('Others', 'Others')], max_length=39),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('Golang', 'Golang'), ('C++)', 'C++)'), ('Others', 'Others')], max_length=41),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='libraries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ajax', 'Ajax'), ('Jquery', 'Jquery'), ('React.js', 'React.js'), ('Keras', 'Keras'), ('Tensorflow', 'Tensorflow'), ('Others', 'Others')], max_length=44),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('React Native', 'React Native'), ('Ionic', 'Ionic'), ('Flutter', 'Flutter'), ('Kivy', 'Kivy'), ('Xamarin', 'Xamarin'), ('Others', 'Others')], max_length=46),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='others',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('UML', 'UML'), ('Firebase', 'Firebase'), ('Docker', 'Docker'), ('GIT', 'GIT'), ('GraphQL', 'GraphQL'), ('Others', 'Others')], max_length=38),
        ),
    ]
